name: hashids2
version: 1.0.1
authors: 
- Iwan Sapoetra <isapoetra@gmail.com>
- Olexandr Leuschenko <olexa.le@gmail.com>
description: Hashids is small library to generate YouTube-like ids from numbers. Use Hashids when you do not want to expose your database ids to the user.
homepage: https://github.com/olexale/hashids
environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: '>=0.12.42 <2.0.0'
  test_coverage: ^0.2.0
